
STATIC_IP_TEMPLATE = "172.32.128.10%d"

Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.define 'gluu-single' do |config|
        # config.vm.box = 'fgrehm/trusty64-lxc'
        # config.vm.box = 'developerinlondon/ubuntu_lxc_xenial_x64'
        config.vm.box = 'generic/ubuntu1604'
        config.vm.network "private_network", ip: STATIC_IP_TEMPLATE % 1
        config.vm.hostname = 'gluu-single'
        config.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get -y install python apt-transport-https
        SHELL

        config.vm.provider "libvirt" do |v|
            v.cpus = 2
            v.memory = 2048
            v.driver = "qemu"
        end
        config.vm.provider "virtualbox" do |v|
            v.cpus = 2
            v.memory = 2048
        end
    end
end