
# Get all servers IP
- hosts: gluu-servers
  become: true
  gather_facts: true
  become_user: root
  become_method: sudo
  tasks:
    - debug:
        msg: "Get IP address: {{ ansible_default_ipv4.address }}"

# Install the main LDAP server and configure it directly else we have to wait the end of replication
- hosts: gluu-configuration
  become: true
  become_user: root
  become_method: sudo
  roles:
    - GuillaumeSmaha.gluu-setup
    - GuillaumeSmaha.gluu-configuration

# Install others servers
- hosts: gluu-servers
  become: true
  become_user: root
  become_method: sudo
  serial: 1
  roles:
    - GuillaumeSmaha.gluu-setup

# Customize servers with oxauth
- hosts: gluu-oxauth
  become: true
  become_user: root
  become_method: sudo
  roles:
    - GuillaumeSmaha.gluu-customization