- hosts: gluu-servers
  become: true
  gather_facts: true
  become_user: root
  become_method: sudo
  tasks:
    - debug:
        msg: "Get IP address: {{ ansible_default_ipv4.address }}"

- hosts: gluu-servers
  become: true
  become_user: root
  become_method: sudo
  serial: 1
  roles:
    - GuillaumeSmaha.gluu-setup

- hosts: gluu-oxauth
  become: true
  become_user: root
  become_method: sudo
  roles:
    - GuillaumeSmaha.gluu-customization

- hosts: gluu-configuration
  become: true
  become_user: root
  become_method: sudo
  roles:
    - GuillaumeSmaha.gluu-configuration
